/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const EntityId = IDL.Text;
export const BookingType = IDL.Variant({
  'ticket' : IDL.Null,
  'tour' : IDL.Null,
  'visa' : IDL.Null,
  'umrah' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const Result_1 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
export const ClientType = IDL.Variant({
  'client' : IDL.Null,
  'supplier' : IDL.Null,
});
export const VoucherEntry = IDL.Record({
  'accountId' : EntityId,
  'credit' : IDL.Float64,
  'accountName' : IDL.Text,
  'debit' : IDL.Float64,
});
export const PaymentMethod = IDL.Variant({
  'bank' : IDL.Null,
  'cash' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : EntityId,
  'pnr' : IDL.Opt(IDL.Text),
  'status' : BookingStatus,
  'clientId' : EntityId,
  'netFare' : IDL.Float64,
  'createdAt' : Timestamp,
  'createdBy' : IDL.Principal,
  'invoiceId' : IDL.Opt(EntityId),
  'sector' : IDL.Opt(IDL.Text),
  'bookingType' : BookingType,
  'travelDate' : IDL.Opt(Timestamp),
  'airline' : IDL.Opt(IDL.Text),
  'profit' : IDL.Float64,
  'saleFare' : IDL.Float64,
});
export const Client = IDL.Record({
  'id' : EntityId,
  'clientType' : ClientType,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'email' : IDL.Opt(IDL.Text),
  'openingBalance' : IDL.Float64,
  'phone' : IDL.Text,
});
export const DashboardStats = IDL.Record({
  'todayTransactions' : IDL.Nat,
  'totalReceivable' : IDL.Float64,
  'totalProfit' : IDL.Float64,
  'totalSales' : IDL.Float64,
  'totalPayable' : IDL.Float64,
});
export const InvoiceStatus = IDL.Variant({
  'paid' : IDL.Null,
  'unpaid' : IDL.Null,
  'partial' : IDL.Null,
});
export const Invoice = IDL.Record({
  'id' : EntityId,
  'due' : IDL.Float64,
  'status' : InvoiceStatus,
  'clientId' : EntityId,
  'bookingId' : EntityId,
  'createdAt' : Timestamp,
  'paid' : IDL.Float64,
  'invoiceNo' : IDL.Text,
  'amount' : IDL.Float64,
});
export const LedgerEntry = IDL.Record({
  'id' : EntityId,
  'balance' : IDL.Float64,
  'date' : Timestamp,
  'description' : IDL.Text,
  'voucherType' : IDL.Text,
  'credit' : IDL.Float64,
  'entityId' : EntityId,
  'entityType' : ClientType,
  'voucherNo' : IDL.Text,
  'debit' : IDL.Float64,
});
export const OutstandingEntry = IDL.Record({
  'due' : IDL.Float64,
  'clientName' : IDL.Text,
  'paid' : IDL.Float64,
  'invoiceNo' : IDL.Text,
  'amount' : IDL.Float64,
});
export const ProfitLossReport = IDL.Record({
  'grossProfit' : IDL.Float64,
  'totalCost' : IDL.Float64,
  'totalSales' : IDL.Float64,
  'netProfit' : IDL.Float64,
});
export const Settings = IDL.Record({
  'invoiceNextNo' : IDL.Nat,
  'voucherNextNo' : IDL.Nat,
  'invoicePrefix' : IDL.Text,
  'voucherPrefix' : IDL.Text,
  'currency' : IDL.Text,
  'agencyName' : IDL.Text,
});
export const TrialBalanceEntry = IDL.Record({
  'credit' : IDL.Float64,
  'accountName' : IDL.Text,
  'debit' : IDL.Float64,
});
export const VoucherType = IDL.Variant({
  'receipt' : IDL.Null,
  'journal' : IDL.Null,
  'contra' : IDL.Null,
  'payment' : IDL.Null,
});
export const Voucher = IDL.Record({
  'id' : EntityId,
  'clientId' : IDL.Opt(EntityId),
  'paymentMethod' : IDL.Opt(PaymentMethod),
  'date' : Timestamp,
  'createdAt' : Timestamp,
  'createdBy' : IDL.Principal,
  'voucherType' : VoucherType,
  'entries' : IDL.Vec(VoucherEntry),
  'voucherNo' : IDL.Text,
  'amount' : IDL.Float64,
  'supplierId' : IDL.Opt(EntityId),
  'remarks' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addBooking' : IDL.Func(
      [
        EntityId,
        BookingType,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(Timestamp),
        IDL.Float64,
        IDL.Float64,
      ],
      [Result_1],
      [],
    ),
  'addClient' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Float64, ClientType],
      [Result_1],
      [],
    ),
  'addContraVoucher' : IDL.Func(
      [Timestamp, IDL.Text, IDL.Text, IDL.Float64, IDL.Opt(IDL.Text)],
      [Result_1],
      [],
    ),
  'addJournalVoucher' : IDL.Func(
      [Timestamp, IDL.Vec(VoucherEntry), IDL.Opt(IDL.Text)],
      [Result_1],
      [],
    ),
  'addPaymentVoucher' : IDL.Func(
      [Timestamp, EntityId, IDL.Float64, PaymentMethod, IDL.Opt(IDL.Text)],
      [Result_1],
      [],
    ),
  'addReceiptVoucher' : IDL.Func(
      [Timestamp, EntityId, IDL.Float64, PaymentMethod, IDL.Opt(IDL.Text)],
      [Result_1],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteClient' : IDL.Func([EntityId], [Result], []),
  'getBookingById' : IDL.Func([EntityId], [IDL.Opt(Booking)], ['query']),
  'getBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClientById' : IDL.Func([EntityId], [IDL.Opt(Client)], ['query']),
  'getClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getInvoiceById' : IDL.Func([EntityId], [IDL.Opt(Invoice)], ['query']),
  'getInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'getInvoicesByClient' : IDL.Func([EntityId], [IDL.Vec(Invoice)], ['query']),
  'getLedgerByEntity' : IDL.Func([EntityId], [IDL.Vec(LedgerEntry)], ['query']),
  'getOutstandingReport' : IDL.Func([], [IDL.Vec(OutstandingEntry)], ['query']),
  'getProfitLossReport' : IDL.Func([], [ProfitLossReport], ['query']),
  'getRunningBalance' : IDL.Func([EntityId], [IDL.Float64], ['query']),
  'getSettings' : IDL.Func([], [Settings], ['query']),
  'getSuppliers' : IDL.Func([], [IDL.Vec(Client)], ['query']),
  'getTrialBalance' : IDL.Func([], [IDL.Vec(TrialBalanceEntry)], ['query']),
  'getVouchers' : IDL.Func([], [IDL.Vec(Voucher)], ['query']),
  'getVouchersByType' : IDL.Func([VoucherType], [IDL.Vec(Voucher)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'updateBooking' : IDL.Func(
      [
        EntityId,
        EntityId,
        BookingType,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(Timestamp),
        IDL.Float64,
        IDL.Float64,
        BookingStatus,
      ],
      [Result],
      [],
    ),
  'updateClient' : IDL.Func(
      [EntityId, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Float64],
      [Result],
      [],
    ),
  'updateSettings' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
      [Result],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const EntityId = IDL.Text;
  const BookingType = IDL.Variant({
    'ticket' : IDL.Null,
    'tour' : IDL.Null,
    'visa' : IDL.Null,
    'umrah' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const Result_1 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const ClientType = IDL.Variant({
    'client' : IDL.Null,
    'supplier' : IDL.Null,
  });
  const VoucherEntry = IDL.Record({
    'accountId' : EntityId,
    'credit' : IDL.Float64,
    'accountName' : IDL.Text,
    'debit' : IDL.Float64,
  });
  const PaymentMethod = IDL.Variant({ 'bank' : IDL.Null, 'cash' : IDL.Null });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : EntityId,
    'pnr' : IDL.Opt(IDL.Text),
    'status' : BookingStatus,
    'clientId' : EntityId,
    'netFare' : IDL.Float64,
    'createdAt' : Timestamp,
    'createdBy' : IDL.Principal,
    'invoiceId' : IDL.Opt(EntityId),
    'sector' : IDL.Opt(IDL.Text),
    'bookingType' : BookingType,
    'travelDate' : IDL.Opt(Timestamp),
    'airline' : IDL.Opt(IDL.Text),
    'profit' : IDL.Float64,
    'saleFare' : IDL.Float64,
  });
  const Client = IDL.Record({
    'id' : EntityId,
    'clientType' : ClientType,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'email' : IDL.Opt(IDL.Text),
    'openingBalance' : IDL.Float64,
    'phone' : IDL.Text,
  });
  const DashboardStats = IDL.Record({
    'todayTransactions' : IDL.Nat,
    'totalReceivable' : IDL.Float64,
    'totalProfit' : IDL.Float64,
    'totalSales' : IDL.Float64,
    'totalPayable' : IDL.Float64,
  });
  const InvoiceStatus = IDL.Variant({
    'paid' : IDL.Null,
    'unpaid' : IDL.Null,
    'partial' : IDL.Null,
  });
  const Invoice = IDL.Record({
    'id' : EntityId,
    'due' : IDL.Float64,
    'status' : InvoiceStatus,
    'clientId' : EntityId,
    'bookingId' : EntityId,
    'createdAt' : Timestamp,
    'paid' : IDL.Float64,
    'invoiceNo' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const LedgerEntry = IDL.Record({
    'id' : EntityId,
    'balance' : IDL.Float64,
    'date' : Timestamp,
    'description' : IDL.Text,
    'voucherType' : IDL.Text,
    'credit' : IDL.Float64,
    'entityId' : EntityId,
    'entityType' : ClientType,
    'voucherNo' : IDL.Text,
    'debit' : IDL.Float64,
  });
  const OutstandingEntry = IDL.Record({
    'due' : IDL.Float64,
    'clientName' : IDL.Text,
    'paid' : IDL.Float64,
    'invoiceNo' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const ProfitLossReport = IDL.Record({
    'grossProfit' : IDL.Float64,
    'totalCost' : IDL.Float64,
    'totalSales' : IDL.Float64,
    'netProfit' : IDL.Float64,
  });
  const Settings = IDL.Record({
    'invoiceNextNo' : IDL.Nat,
    'voucherNextNo' : IDL.Nat,
    'invoicePrefix' : IDL.Text,
    'voucherPrefix' : IDL.Text,
    'currency' : IDL.Text,
    'agencyName' : IDL.Text,
  });
  const TrialBalanceEntry = IDL.Record({
    'credit' : IDL.Float64,
    'accountName' : IDL.Text,
    'debit' : IDL.Float64,
  });
  const VoucherType = IDL.Variant({
    'receipt' : IDL.Null,
    'journal' : IDL.Null,
    'contra' : IDL.Null,
    'payment' : IDL.Null,
  });
  const Voucher = IDL.Record({
    'id' : EntityId,
    'clientId' : IDL.Opt(EntityId),
    'paymentMethod' : IDL.Opt(PaymentMethod),
    'date' : Timestamp,
    'createdAt' : Timestamp,
    'createdBy' : IDL.Principal,
    'voucherType' : VoucherType,
    'entries' : IDL.Vec(VoucherEntry),
    'voucherNo' : IDL.Text,
    'amount' : IDL.Float64,
    'supplierId' : IDL.Opt(EntityId),
    'remarks' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addBooking' : IDL.Func(
        [
          EntityId,
          BookingType,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(Timestamp),
          IDL.Float64,
          IDL.Float64,
        ],
        [Result_1],
        [],
      ),
    'addClient' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Float64, ClientType],
        [Result_1],
        [],
      ),
    'addContraVoucher' : IDL.Func(
        [Timestamp, IDL.Text, IDL.Text, IDL.Float64, IDL.Opt(IDL.Text)],
        [Result_1],
        [],
      ),
    'addJournalVoucher' : IDL.Func(
        [Timestamp, IDL.Vec(VoucherEntry), IDL.Opt(IDL.Text)],
        [Result_1],
        [],
      ),
    'addPaymentVoucher' : IDL.Func(
        [Timestamp, EntityId, IDL.Float64, PaymentMethod, IDL.Opt(IDL.Text)],
        [Result_1],
        [],
      ),
    'addReceiptVoucher' : IDL.Func(
        [Timestamp, EntityId, IDL.Float64, PaymentMethod, IDL.Opt(IDL.Text)],
        [Result_1],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteClient' : IDL.Func([EntityId], [Result], []),
    'getBookingById' : IDL.Func([EntityId], [IDL.Opt(Booking)], ['query']),
    'getBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClientById' : IDL.Func([EntityId], [IDL.Opt(Client)], ['query']),
    'getClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getInvoiceById' : IDL.Func([EntityId], [IDL.Opt(Invoice)], ['query']),
    'getInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'getInvoicesByClient' : IDL.Func([EntityId], [IDL.Vec(Invoice)], ['query']),
    'getLedgerByEntity' : IDL.Func(
        [EntityId],
        [IDL.Vec(LedgerEntry)],
        ['query'],
      ),
    'getOutstandingReport' : IDL.Func(
        [],
        [IDL.Vec(OutstandingEntry)],
        ['query'],
      ),
    'getProfitLossReport' : IDL.Func([], [ProfitLossReport], ['query']),
    'getRunningBalance' : IDL.Func([EntityId], [IDL.Float64], ['query']),
    'getSettings' : IDL.Func([], [Settings], ['query']),
    'getSuppliers' : IDL.Func([], [IDL.Vec(Client)], ['query']),
    'getTrialBalance' : IDL.Func([], [IDL.Vec(TrialBalanceEntry)], ['query']),
    'getVouchers' : IDL.Func([], [IDL.Vec(Voucher)], ['query']),
    'getVouchersByType' : IDL.Func(
        [VoucherType],
        [IDL.Vec(Voucher)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'updateBooking' : IDL.Func(
        [
          EntityId,
          EntityId,
          BookingType,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(Timestamp),
          IDL.Float64,
          IDL.Float64,
          BookingStatus,
        ],
        [Result],
        [],
      ),
    'updateClient' : IDL.Func(
        [EntityId, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Float64],
        [Result],
        [],
      ),
    'updateSettings' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
        [Result],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };