/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : EntityId,
  'pnr' : [] | [string],
  'status' : BookingStatus,
  'clientId' : EntityId,
  'netFare' : number,
  'createdAt' : Timestamp,
  'createdBy' : Principal,
  'invoiceId' : [] | [EntityId],
  'sector' : [] | [string],
  'bookingType' : BookingType,
  'travelDate' : [] | [Timestamp],
  'airline' : [] | [string],
  'profit' : number,
  'saleFare' : number,
}
export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'confirmed' : null };
export type BookingType = { 'ticket' : null } |
  { 'tour' : null } |
  { 'visa' : null } |
  { 'umrah' : null };
export interface Client {
  'id' : EntityId,
  'clientType' : ClientType,
  'name' : string,
  'createdAt' : Timestamp,
  'email' : [] | [string],
  'openingBalance' : number,
  'phone' : string,
}
export type ClientType = { 'client' : null } |
  { 'supplier' : null };
export interface DashboardStats {
  'todayTransactions' : bigint,
  'totalReceivable' : number,
  'totalProfit' : number,
  'totalSales' : number,
  'totalPayable' : number,
}
export type EntityId = string;
export interface Invoice {
  'id' : EntityId,
  'due' : number,
  'status' : InvoiceStatus,
  'clientId' : EntityId,
  'bookingId' : EntityId,
  'createdAt' : Timestamp,
  'paid' : number,
  'invoiceNo' : string,
  'amount' : number,
}
export type InvoiceStatus = { 'paid' : null } |
  { 'unpaid' : null } |
  { 'partial' : null };
export interface LedgerEntry {
  'id' : EntityId,
  'balance' : number,
  'date' : Timestamp,
  'description' : string,
  'voucherType' : string,
  'credit' : number,
  'entityId' : EntityId,
  'entityType' : ClientType,
  'voucherNo' : string,
  'debit' : number,
}
export interface OutstandingEntry {
  'due' : number,
  'clientName' : string,
  'paid' : number,
  'invoiceNo' : string,
  'amount' : number,
}
export type PaymentMethod = { 'bank' : null } |
  { 'cash' : null };
export interface ProfitLossReport {
  'grossProfit' : number,
  'totalCost' : number,
  'totalSales' : number,
  'netProfit' : number,
}
export type Result = { 'ok' : null } |
  { 'err' : string };
export type Result_1 = { 'ok' : string } |
  { 'err' : string };
export interface Settings {
  'invoiceNextNo' : bigint,
  'voucherNextNo' : bigint,
  'invoicePrefix' : string,
  'voucherPrefix' : string,
  'currency' : string,
  'agencyName' : string,
}
export type Timestamp = bigint;
export interface TrialBalanceEntry {
  'credit' : number,
  'accountName' : string,
  'debit' : number,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Voucher {
  'id' : EntityId,
  'clientId' : [] | [EntityId],
  'paymentMethod' : [] | [PaymentMethod],
  'date' : Timestamp,
  'createdAt' : Timestamp,
  'createdBy' : Principal,
  'voucherType' : VoucherType,
  'entries' : Array<VoucherEntry>,
  'voucherNo' : string,
  'amount' : number,
  'supplierId' : [] | [EntityId],
  'remarks' : [] | [string],
}
export interface VoucherEntry {
  'accountId' : EntityId,
  'credit' : number,
  'accountName' : string,
  'debit' : number,
}
export type VoucherType = { 'receipt' : null } |
  { 'journal' : null } |
  { 'contra' : null } |
  { 'payment' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addBooking' : ActorMethod<
    [
      EntityId,
      BookingType,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [Timestamp],
      number,
      number,
    ],
    Result_1
  >,
  'addClient' : ActorMethod<
    [string, string, [] | [string], number, ClientType],
    Result_1
  >,
  'addContraVoucher' : ActorMethod<
    [Timestamp, string, string, number, [] | [string]],
    Result_1
  >,
  'addJournalVoucher' : ActorMethod<
    [Timestamp, Array<VoucherEntry>, [] | [string]],
    Result_1
  >,
  'addPaymentVoucher' : ActorMethod<
    [Timestamp, EntityId, number, PaymentMethod, [] | [string]],
    Result_1
  >,
  'addReceiptVoucher' : ActorMethod<
    [Timestamp, EntityId, number, PaymentMethod, [] | [string]],
    Result_1
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteClient' : ActorMethod<[EntityId], Result>,
  'getBookingById' : ActorMethod<[EntityId], [] | [Booking]>,
  'getBookings' : ActorMethod<[], Array<Booking>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClientById' : ActorMethod<[EntityId], [] | [Client]>,
  'getClients' : ActorMethod<[], Array<Client>>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getInvoiceById' : ActorMethod<[EntityId], [] | [Invoice]>,
  'getInvoices' : ActorMethod<[], Array<Invoice>>,
  'getInvoicesByClient' : ActorMethod<[EntityId], Array<Invoice>>,
  'getLedgerByEntity' : ActorMethod<[EntityId], Array<LedgerEntry>>,
  'getOutstandingReport' : ActorMethod<[], Array<OutstandingEntry>>,
  'getProfitLossReport' : ActorMethod<[], ProfitLossReport>,
  'getRunningBalance' : ActorMethod<[EntityId], number>,
  'getSettings' : ActorMethod<[], Settings>,
  'getSuppliers' : ActorMethod<[], Array<Client>>,
  'getTrialBalance' : ActorMethod<[], Array<TrialBalanceEntry>>,
  'getVouchers' : ActorMethod<[], Array<Voucher>>,
  'getVouchersByType' : ActorMethod<[VoucherType], Array<Voucher>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'updateBooking' : ActorMethod<
    [
      EntityId,
      EntityId,
      BookingType,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [Timestamp],
      number,
      number,
      BookingStatus,
    ],
    Result
  >,
  'updateClient' : ActorMethod<
    [EntityId, string, string, [] | [string], number],
    Result
  >,
  'updateSettings' : ActorMethod<
    [string, string, bigint, string, bigint, string],
    Result
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];