/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface VoucherEntry {
    accountId: EntityId;
    credit: number;
    accountName: string;
    debit: number;
}
export type Timestamp = bigint;
export interface OutstandingEntry {
    due: number;
    clientName: string;
    paid: number;
    invoiceNo: string;
    amount: number;
}
export type EntityId = string;
export interface ProfitLossReport {
    grossProfit: number;
    totalCost: number;
    totalSales: number;
    netProfit: number;
}
export interface Invoice {
    id: EntityId;
    due: number;
    status: InvoiceStatus;
    clientId: EntityId;
    bookingId: EntityId;
    createdAt: Timestamp;
    paid: number;
    invoiceNo: string;
    amount: number;
}
export type Result_1 = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export interface LedgerEntry {
    id: EntityId;
    balance: number;
    date: Timestamp;
    description: string;
    voucherType: string;
    credit: number;
    entityId: EntityId;
    entityType: ClientType;
    voucherNo: string;
    debit: number;
}
export interface DashboardStats {
    todayTransactions: bigint;
    totalReceivable: number;
    totalProfit: number;
    totalSales: number;
    totalPayable: number;
}
export interface TrialBalanceEntry {
    credit: number;
    accountName: string;
    debit: number;
}
export interface Voucher {
    id: EntityId;
    clientId?: EntityId;
    paymentMethod?: PaymentMethod;
    date: Timestamp;
    createdAt: Timestamp;
    createdBy: Principal;
    voucherType: VoucherType;
    entries: Array<VoucherEntry>;
    voucherNo: string;
    amount: number;
    supplierId?: EntityId;
    remarks?: string;
}
export interface Settings {
    invoiceNextNo: bigint;
    voucherNextNo: bigint;
    invoicePrefix: string;
    voucherPrefix: string;
    currency: string;
    agencyName: string;
}
export type Result = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export interface Booking {
    id: EntityId;
    pnr?: string;
    status: BookingStatus;
    clientId: EntityId;
    netFare: number;
    createdAt: Timestamp;
    createdBy: Principal;
    invoiceId?: EntityId;
    sector?: string;
    bookingType: BookingType;
    travelDate?: Timestamp;
    airline?: string;
    profit: number;
    saleFare: number;
}
export interface Client {
    id: EntityId;
    clientType: ClientType;
    name: string;
    createdAt: Timestamp;
    email?: string;
    openingBalance: number;
    phone: string;
}
export enum BookingStatus {
    cancelled = "cancelled",
    pending = "pending",
    confirmed = "confirmed"
}
export enum BookingType {
    ticket = "ticket",
    tour = "tour",
    visa = "visa",
    umrah = "umrah"
}
export enum ClientType {
    client = "client",
    supplier = "supplier"
}
export enum InvoiceStatus {
    paid = "paid",
    unpaid = "unpaid",
    partial = "partial"
}
export enum PaymentMethod {
    bank = "bank",
    cash = "cash"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum VoucherType {
    receipt = "receipt",
    journal = "journal",
    contra = "contra",
    payment = "payment"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    addBooking(clientId: EntityId, bookingType: BookingType, pnr: string | null, sector: string | null, airline: string | null, travelDate: Timestamp | null, netFare: number, saleFare: number): Promise<Result_1>;
    addClient(name: string, phone: string, email: string | null, openingBalance: number, clientType: ClientType): Promise<Result_1>;
    addContraVoucher(date: Timestamp, fromAccount: string, toAccount: string, amount: number, remarks: string | null): Promise<Result_1>;
    addJournalVoucher(date: Timestamp, entries: Array<VoucherEntry>, remarks: string | null): Promise<Result_1>;
    addPaymentVoucher(date: Timestamp, supplierId: EntityId, amount: number, paymentMethod: PaymentMethod, remarks: string | null): Promise<Result_1>;
    addReceiptVoucher(date: Timestamp, clientId: EntityId, amount: number, paymentMethod: PaymentMethod, remarks: string | null): Promise<Result_1>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteClient(id: EntityId): Promise<Result>;
    getBookingById(id: EntityId): Promise<Booking | null>;
    getBookings(): Promise<Array<Booking>>;
    getCallerUserRole(): Promise<UserRole>;
    getClientById(id: EntityId): Promise<Client | null>;
    getClients(): Promise<Array<Client>>;
    getDashboardStats(): Promise<DashboardStats>;
    getInvoiceById(id: EntityId): Promise<Invoice | null>;
    getInvoices(): Promise<Array<Invoice>>;
    getInvoicesByClient(clientId: EntityId): Promise<Array<Invoice>>;
    getLedgerByEntity(entityId: EntityId): Promise<Array<LedgerEntry>>;
    getOutstandingReport(): Promise<Array<OutstandingEntry>>;
    getProfitLossReport(): Promise<ProfitLossReport>;
    getRunningBalance(entityId: EntityId): Promise<number>;
    getSettings(): Promise<Settings>;
    getSuppliers(): Promise<Array<Client>>;
    getTrialBalance(): Promise<Array<TrialBalanceEntry>>;
    getVouchers(): Promise<Array<Voucher>>;
    getVouchersByType(voucherType: VoucherType): Promise<Array<Voucher>>;
    isCallerAdmin(): Promise<boolean>;
    updateBooking(id: EntityId, clientId: EntityId, bookingType: BookingType, pnr: string | null, sector: string | null, airline: string | null, travelDate: Timestamp | null, netFare: number, saleFare: number, status: BookingStatus): Promise<Result>;
    updateClient(id: EntityId, name: string, phone: string, email: string | null, openingBalance: number): Promise<Result>;
    updateSettings(currency: string, invoicePrefix: string, invoiceNextNo: bigint, voucherPrefix: string, voucherNextNo: bigint, agencyName: string): Promise<Result>;
}
import type { Booking as _Booking, BookingStatus as _BookingStatus, BookingType as _BookingType, Client as _Client, ClientType as _ClientType, EntityId as _EntityId, Invoice as _Invoice, InvoiceStatus as _InvoiceStatus, LedgerEntry as _LedgerEntry, PaymentMethod as _PaymentMethod, Result as _Result, Result_1 as _Result_1, Timestamp as _Timestamp, UserRole as _UserRole, Voucher as _Voucher, VoucherEntry as _VoucherEntry, VoucherType as _VoucherType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addBooking(arg0: EntityId, arg1: BookingType, arg2: string | null, arg3: string | null, arg4: string | null, arg5: Timestamp | null, arg6: number, arg7: number): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.addBooking(arg0, to_candid_BookingType_n1(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
                return from_candid_Result_1_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBooking(arg0, to_candid_BookingType_n1(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
            return from_candid_Result_1_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async addClient(arg0: string, arg1: string, arg2: string | null, arg3: number, arg4: ClientType): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.addClient(arg0, arg1, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_ClientType_n7(this._uploadFile, this._downloadFile, arg4));
                return from_candid_Result_1_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addClient(arg0, arg1, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_ClientType_n7(this._uploadFile, this._downloadFile, arg4));
            return from_candid_Result_1_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async addContraVoucher(arg0: Timestamp, arg1: string, arg2: string, arg3: number, arg4: string | null): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.addContraVoucher(arg0, arg1, arg2, arg3, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg4));
                return from_candid_Result_1_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addContraVoucher(arg0, arg1, arg2, arg3, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg4));
            return from_candid_Result_1_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async addJournalVoucher(arg0: Timestamp, arg1: Array<VoucherEntry>, arg2: string | null): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.addJournalVoucher(arg0, arg1, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Result_1_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addJournalVoucher(arg0, arg1, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Result_1_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async addPaymentVoucher(arg0: Timestamp, arg1: EntityId, arg2: number, arg3: PaymentMethod, arg4: string | null): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.addPaymentVoucher(arg0, arg1, arg2, to_candid_PaymentMethod_n9(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg4));
                return from_candid_Result_1_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPaymentVoucher(arg0, arg1, arg2, to_candid_PaymentMethod_n9(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg4));
            return from_candid_Result_1_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async addReceiptVoucher(arg0: Timestamp, arg1: EntityId, arg2: number, arg3: PaymentMethod, arg4: string | null): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.addReceiptVoucher(arg0, arg1, arg2, to_candid_PaymentMethod_n9(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg4));
                return from_candid_Result_1_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReceiptVoucher(arg0, arg1, arg2, to_candid_PaymentMethod_n9(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg4));
            return from_candid_Result_1_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteClient(arg0: EntityId): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteClient(arg0);
                return from_candid_Result_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteClient(arg0);
            return from_candid_Result_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingById(arg0: EntityId): Promise<Booking | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingById(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingById(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookings();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookings();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClientById(arg0: EntityId): Promise<Client | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getClientById(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClientById(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClients(): Promise<Array<Client>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClients();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClients();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getInvoiceById(arg0: EntityId): Promise<Invoice | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoiceById(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoiceById(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInvoices(): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoices();
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoices();
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInvoicesByClient(arg0: EntityId): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoicesByClient(arg0);
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoicesByClient(arg0);
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLedgerByEntity(arg0: EntityId): Promise<Array<LedgerEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLedgerByEntity(arg0);
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLedgerByEntity(arg0);
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOutstandingReport(): Promise<Array<OutstandingEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOutstandingReport();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOutstandingReport();
            return result;
        }
    }
    async getProfitLossReport(): Promise<ProfitLossReport> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfitLossReport();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfitLossReport();
            return result;
        }
    }
    async getRunningBalance(arg0: EntityId): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getRunningBalance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRunningBalance(arg0);
            return result;
        }
    }
    async getSettings(): Promise<Settings> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettings();
            return result;
        }
    }
    async getSuppliers(): Promise<Array<Client>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSuppliers();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSuppliers();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrialBalance(): Promise<Array<TrialBalanceEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrialBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrialBalance();
            return result;
        }
    }
    async getVouchers(): Promise<Array<Voucher>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVouchers();
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVouchers();
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVouchersByType(arg0: VoucherType): Promise<Array<Voucher>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVouchersByType(to_candid_VoucherType_n51(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVouchersByType(to_candid_VoucherType_n51(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async updateBooking(arg0: EntityId, arg1: EntityId, arg2: BookingType, arg3: string | null, arg4: string | null, arg5: string | null, arg6: Timestamp | null, arg7: number, arg8: number, arg9: BookingStatus): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBooking(arg0, arg1, to_candid_BookingType_n1(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg6), arg7, arg8, to_candid_BookingStatus_n53(this._uploadFile, this._downloadFile, arg9));
                return from_candid_Result_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBooking(arg0, arg1, to_candid_BookingType_n1(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg6), arg7, arg8, to_candid_BookingStatus_n53(this._uploadFile, this._downloadFile, arg9));
            return from_candid_Result_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateClient(arg0: EntityId, arg1: string, arg2: string, arg3: string | null, arg4: number): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClient(arg0, arg1, arg2, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg3), arg4);
                return from_candid_Result_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClient(arg0, arg1, arg2, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg3), arg4);
            return from_candid_Result_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSettings(arg0: string, arg1: string, arg2: bigint, arg3: string, arg4: bigint, arg5: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSettings(arg0, arg1, arg2, arg3, arg4, arg5);
                return from_candid_Result_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSettings(arg0, arg1, arg2, arg3, arg4, arg5);
            return from_candid_Result_n13(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_BookingStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_BookingType_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingType): BookingType {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Booking_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_ClientType_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClientType): ClientType {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_Client_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Client): Client {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_InvoiceStatus_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InvoiceStatus): InvoiceStatus {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_Invoice_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Invoice): Invoice {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_LedgerEntry_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LedgerEntry): LedgerEntry {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_VoucherType_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VoucherType): VoucherType {
    return from_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function from_candid_Voucher_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Voucher): Voucher {
    return from_candid_record_n45(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Booking]): Booking | null {
    return value.length === 0 ? null : from_candid_Booking_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_EntityId]): EntityId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Client]): Client | null {
    return value.length === 0 ? null : from_candid_Client_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Invoice]): Invoice | null {
    return value.length === 0 ? null : from_candid_Invoice_n35(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PaymentMethod]): PaymentMethod | null {
    return value.length === 0 ? null : from_candid_PaymentMethod_n47(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EntityId;
    pnr: [] | [string];
    status: _BookingStatus;
    clientId: _EntityId;
    netFare: number;
    createdAt: _Timestamp;
    createdBy: Principal;
    invoiceId: [] | [_EntityId];
    sector: [] | [string];
    bookingType: _BookingType;
    travelDate: [] | [_Timestamp];
    airline: [] | [string];
    profit: number;
    saleFare: number;
}): {
    id: EntityId;
    pnr?: string;
    status: BookingStatus;
    clientId: EntityId;
    netFare: number;
    createdAt: Timestamp;
    createdBy: Principal;
    invoiceId?: EntityId;
    sector?: string;
    bookingType: BookingType;
    travelDate?: Timestamp;
    airline?: string;
    profit: number;
    saleFare: number;
} {
    return {
        id: value.id,
        pnr: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.pnr)),
        status: from_candid_BookingStatus_n19(_uploadFile, _downloadFile, value.status),
        clientId: value.clientId,
        netFare: value.netFare,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        invoiceId: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.invoiceId)),
        sector: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.sector)),
        bookingType: from_candid_BookingType_n22(_uploadFile, _downloadFile, value.bookingType),
        travelDate: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.travelDate)),
        airline: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.airline)),
        profit: value.profit,
        saleFare: value.saleFare
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EntityId;
    clientType: _ClientType;
    name: string;
    createdAt: _Timestamp;
    email: [] | [string];
    openingBalance: number;
    phone: string;
}): {
    id: EntityId;
    clientType: ClientType;
    name: string;
    createdAt: Timestamp;
    email?: string;
    openingBalance: number;
    phone: string;
} {
    return {
        id: value.id,
        clientType: from_candid_ClientType_n31(_uploadFile, _downloadFile, value.clientType),
        name: value.name,
        createdAt: value.createdAt,
        email: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.email)),
        openingBalance: value.openingBalance,
        phone: value.phone
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EntityId;
    due: number;
    status: _InvoiceStatus;
    clientId: _EntityId;
    bookingId: _EntityId;
    createdAt: _Timestamp;
    paid: number;
    invoiceNo: string;
    amount: number;
}): {
    id: EntityId;
    due: number;
    status: InvoiceStatus;
    clientId: EntityId;
    bookingId: EntityId;
    createdAt: Timestamp;
    paid: number;
    invoiceNo: string;
    amount: number;
} {
    return {
        id: value.id,
        due: value.due,
        status: from_candid_InvoiceStatus_n37(_uploadFile, _downloadFile, value.status),
        clientId: value.clientId,
        bookingId: value.bookingId,
        createdAt: value.createdAt,
        paid: value.paid,
        invoiceNo: value.invoiceNo,
        amount: value.amount
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EntityId;
    balance: number;
    date: _Timestamp;
    description: string;
    voucherType: string;
    credit: number;
    entityId: _EntityId;
    entityType: _ClientType;
    voucherNo: string;
    debit: number;
}): {
    id: EntityId;
    balance: number;
    date: Timestamp;
    description: string;
    voucherType: string;
    credit: number;
    entityId: EntityId;
    entityType: ClientType;
    voucherNo: string;
    debit: number;
} {
    return {
        id: value.id,
        balance: value.balance,
        date: value.date,
        description: value.description,
        voucherType: value.voucherType,
        credit: value.credit,
        entityId: value.entityId,
        entityType: from_candid_ClientType_n31(_uploadFile, _downloadFile, value.entityType),
        voucherNo: value.voucherNo,
        debit: value.debit
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EntityId;
    clientId: [] | [_EntityId];
    paymentMethod: [] | [_PaymentMethod];
    date: _Timestamp;
    createdAt: _Timestamp;
    createdBy: Principal;
    voucherType: _VoucherType;
    entries: Array<_VoucherEntry>;
    voucherNo: string;
    amount: number;
    supplierId: [] | [_EntityId];
    remarks: [] | [string];
}): {
    id: EntityId;
    clientId?: EntityId;
    paymentMethod?: PaymentMethod;
    date: Timestamp;
    createdAt: Timestamp;
    createdBy: Principal;
    voucherType: VoucherType;
    entries: Array<VoucherEntry>;
    voucherNo: string;
    amount: number;
    supplierId?: EntityId;
    remarks?: string;
} {
    return {
        id: value.id,
        clientId: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.clientId)),
        paymentMethod: record_opt_to_undefined(from_candid_opt_n46(_uploadFile, _downloadFile, value.paymentMethod)),
        date: value.date,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        voucherType: from_candid_VoucherType_n49(_uploadFile, _downloadFile, value.voucherType),
        entries: value.entries,
        voucherNo: value.voucherNo,
        amount: value.amount,
        supplierId: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.supplierId)),
        remarks: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.remarks))
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    confirmed: null;
}): BookingStatus {
    return "cancelled" in value ? BookingStatus.cancelled : "pending" in value ? BookingStatus.pending : "confirmed" in value ? BookingStatus.confirmed : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ticket: null;
} | {
    tour: null;
} | {
    visa: null;
} | {
    umrah: null;
}): BookingType {
    return "ticket" in value ? BookingType.ticket : "tour" in value ? BookingType.tour : "visa" in value ? BookingType.visa : "umrah" in value ? BookingType.umrah : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    client: null;
} | {
    supplier: null;
}): ClientType {
    return "client" in value ? ClientType.client : "supplier" in value ? ClientType.supplier : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paid: null;
} | {
    unpaid: null;
} | {
    partial: null;
}): InvoiceStatus {
    return "paid" in value ? InvoiceStatus.paid : "unpaid" in value ? InvoiceStatus.unpaid : "partial" in value ? InvoiceStatus.partial : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bank: null;
} | {
    cash: null;
}): PaymentMethod {
    return "bank" in value ? PaymentMethod.bank : "cash" in value ? PaymentMethod.cash : value;
}
function from_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    receipt: null;
} | {
    journal: null;
} | {
    contra: null;
} | {
    payment: null;
}): VoucherType {
    return "receipt" in value ? VoucherType.receipt : "journal" in value ? VoucherType.journal : "contra" in value ? VoucherType.contra : "payment" in value ? VoucherType.payment : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Client>): Array<Client> {
    return value.map((x)=>from_candid_Client_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Invoice>): Array<Invoice> {
    return value.map((x)=>from_candid_Invoice_n35(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LedgerEntry>): Array<LedgerEntry> {
    return value.map((x)=>from_candid_LedgerEntry_n41(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Voucher>): Array<Voucher> {
    return value.map((x)=>from_candid_Voucher_n44(_uploadFile, _downloadFile, x));
}
function to_candid_BookingStatus_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): _BookingStatus {
    return to_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function to_candid_BookingType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingType): _BookingType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_ClientType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClientType): _ClientType {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_VoucherType_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VoucherType): _VoucherType {
    return to_candid_variant_n52(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Timestamp | null): [] | [_Timestamp] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    bank: null;
} | {
    cash: null;
} {
    return value == PaymentMethod.bank ? {
        bank: null
    } : value == PaymentMethod.cash ? {
        cash: null
    } : value;
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingType): {
    ticket: null;
} | {
    tour: null;
} | {
    visa: null;
} | {
    umrah: null;
} {
    return value == BookingType.ticket ? {
        ticket: null
    } : value == BookingType.tour ? {
        tour: null
    } : value == BookingType.visa ? {
        visa: null
    } : value == BookingType.umrah ? {
        umrah: null
    } : value;
}
function to_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VoucherType): {
    receipt: null;
} | {
    journal: null;
} | {
    contra: null;
} | {
    payment: null;
} {
    return value == VoucherType.receipt ? {
        receipt: null
    } : value == VoucherType.journal ? {
        journal: null
    } : value == VoucherType.contra ? {
        contra: null
    } : value == VoucherType.payment ? {
        payment: null
    } : value;
}
function to_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    confirmed: null;
} {
    return value == BookingStatus.cancelled ? {
        cancelled: null
    } : value == BookingStatus.pending ? {
        pending: null
    } : value == BookingStatus.confirmed ? {
        confirmed: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClientType): {
    client: null;
} | {
    supplier: null;
} {
    return value == ClientType.client ? {
        client: null
    } : value == ClientType.supplier ? {
        supplier: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
